### ISSUE TITLE
训练速度

### ISSUE THREAD

**Issue by ycdhqzhiai** [610265158/face_landmark#10]
@610265158  batch 128 训练速度巨慢无比，10个iter要2-3min, 2块2080卡，你那边速度多少啊

**Comment by 610265158** [comment]
> @610265158 batch 128 训练速度巨慢无比，10个iter要2-3min, 2块2080卡，你那边速度多少啊

我这还好，大概一两天就能出结果，

我猜到是什么问题了，应该是数据那块的瓶颈，但是我又没办法解，你可以打个时间戳看看取一次数据的时间。

能贴一下log么，我想看一下，顺便再问一下机器的负载如何

**Comment by ycdhqzhiai** [comment]
![image](https://user-images.githubusercontent.com/12273405/67755669-7dc8b780-fa73-11e9-8fc3-ad144cae657a.png)
![image](https://user-images.githubusercontent.com/12273405/67756632-4ce98200-fa75-11e9-8494-537856c8adb4.png)

前面说2-3min是在训练两个模型，而且说错了batch是256，现在把所有服务都关掉，只训这一个，batch 256，差不多1min左右10个iter，依然很慢，CPU在25%左右
![image](https://user-images.githubusercontent.com/12273405/67756889-caad8d80-fa75-11e9-8fc8-12b464412170.png)

**Comment by ycdhqzhiai** [comment]
![image](https://user-images.githubusercontent.com/12273405/67756962-e87af280-fa75-11e9-9a83-3190bd181eff.png)
前面看错了，以这个为准，batch size 256 ,差不多1min 10个iter,cpu在15%左右
![image](https://user-images.githubusercontent.com/12273405/67757284-7951ce00-fa76-11e9-968d-f8907a9f5ccb.png)

**Comment by 610265158** [comment]
cpu preprare data的时候消耗时间有点长， 把batch size 改小一点吧，
还有opencv的多线程最好关掉，

建议用自己pc做，可以试一下是不是速度快了

**Comment by ycdhqzhiai** [comment]
好的，谢谢
