### ISSUE TITLE
想问一下训练的最终指标是多少？

### ISSUE THREAD

**Issue by XP-CHRC** [610265158/face_landmark#11]
请问您最后在Mobilenet V2上训练的指标是多少(IPN or ION)？

**Comment by 610265158** [comment]
> 请问您最后在Mobilenet V2上训练的指标是多少(IPN or ION)？

hi, 
I did not try to measure any metrics, there I mainly concern about the loss value. Sorry for that.

**Comment by XP-CHRC** [comment]
@610265158 非常感谢您的回复，请问最终的loss是多少呢？并且您的工程可以基于CPU训练么？我尝试了简单的更改代码使其能够运行在CPU上，但是我不是太了解分布式训练，并没有成功。

**Comment by 610265158** [comment]
> @610265158 非常感谢您的回复，请问最终的loss是多少呢？并且您的工程可以基于CPU训练么？我尝试了简单的更改代码使其能够运行在CPU上，但是我不是太了解分布式训练，并没有成功。

loss大概在4上下，
改成cpu的话，
把train.py 40行   
devices = ['/device:CPU:{}'.format(i) for i in range(cfg.TRAIN.num_gpu)]
strategy = tf.distribute.MirroredStrategy(devices)
cpu可能会慢一些，加载一下训好的模型参数吧

**Comment by chaotiaor** [comment]
你好，我在试图把你用tensorflow的模型转化为pytorch的模型，但是，模型中的关键词命名并没有在工程中找到，然后，我使用tensorbord可视化你的模型，也无法可视化出来，所以我想问一下你模型中的结构是怎么的。我用的是tensorflow 1.14的版本

**Comment by 610265158** [comment]
> 你好，我在试图把你用tensorflow的模型转化为pytorch的模型，但是，模型中的关键词命名并没有在工程中找到，然后，我使用tensorbord可视化你的模型，也无法可视化出来，所以我想问一下你模型中的结构是怎么的。我用的是tensorflow 1.14的版本

hi,
我觉得这不是一个很方便的事情，
为什么要迁移到pytorch呢

**Comment by chaotiaor** [comment]
我准备在工程里直接布置你训练出来的模型，但是，用opencv里的dnn板块不能直接读取，安装TensorFlow的c++版本太过费时间，所以我就打算把它转成pytorch的，要是不好搞的话，我只有用pytorch重写一次，然后再进行训练了。



---原始邮件---
发件人: "Lz"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 晚上7:38
收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"rong"<zhaortiang@foxmail.com&gt;;
主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11)


 
你好，我在试图把你用tensorflow的模型转化为pytorch的模型，但是，模型中的关键词命名并没有在工程中找到，然后，我使用tensorbord可视化你的模型，也无法可视化出来，所以我想问一下你模型中的结构是怎么的。我用的是tensorflow 1.14的版本
  
hi,
 我觉得这不是一个很方便的事情，
 为什么要迁移到pytorch呢

**Comment by 610265158** [comment]
> 我准备在工程里直接布置你训练出来的模型，但是，用opencv里的dnn板块不能直接读取，安装TensorFlow的c++版本太过费时间，所以我就打算把它转成pytorch的，要是不好搞的话，我只有用pytorch重写一次，然后再进行训练了。
> […](#)
> ---原始邮件--- 发件人: "Lz"<notifications@github.com&gt; 发送时间: 2019年11月13日(星期三) 晚上7:38 收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"rong"<zhaortiang@foxmail.com&gt;; 主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11) 你好，我在试图把你用tensorflow的模型转化为pytorch的模型，但是，模型中的关键词命名并没有在工程中找到，然后，我使用tensorbord可视化你的模型，也无法可视化出来，所以我想问一下你模型中的结构是怎么的。我用的是tensorflow 1.14的版本 hi, 我觉得这不是一个很方便的事情， 为什么要迁移到pytorch呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

结构是一个类似shufflenet 的网络，试一下tflite？
转换的话，有时间我来搞一下，如果pytorch更方便的话，我可以帮助迁移到pytorch上面

**Comment by chaotiaor** [comment]
好的，非常感谢你的回复，我明天会继续尝试一下，不过，我可能会用pytorch再写一次，然后把模型转成c++，测试它是不是可以在工程中进行应用。之所以使用pytorch，主要是我对TensorFlow已经不是很熟悉了，现在的主流好像还是TensorFlow。



---原始邮件---
发件人: "Lz"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 晚上7:52
收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"rong"<zhaortiang@foxmail.com&gt;;
主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11)


 
我准备在工程里直接布置你训练出来的模型，但是，用opencv里的dnn板块不能直接读取，安装TensorFlow的c++版本太过费时间，所以我就打算把它转成pytorch的，要是不好搞的话，我只有用pytorch重写一次，然后再进行训练了。
 …
 ---原始邮件--- 发件人: "Lz"<notifications@github.com&gt; 发送时间: 2019年11月13日(星期三) 晚上7:38 收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"rong"<zhaortiang@foxmail.com&gt;; 主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11) 你好，我在试图把你用tensorflow的模型转化为pytorch的模型，但是，模型中的关键词命名并没有在工程中找到，然后，我使用tensorbord可视化你的模型，也无法可视化出来，所以我想问一下你模型中的结构是怎么的。我用的是tensorflow 1.14的版本 hi, 我觉得这不是一个很方便的事情， 为什么要迁移到pytorch呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
结构是一个类似shufflenet 的网络，试一下tflite？
 转换的话，有时间我来搞一下，如果pytorch更方便的话，我可以帮助迁移到pytorch上面

**Comment by chaotiaor** [comment]
你好，我使用tensorflow 2.0，使用你项目中转化模型成为tflite格式的代码进行转化，会报错，这是为什么呢

**Comment by 610265158** [comment]
> 你好，我使用tensorflow 2.0，使用你项目中转化模型成为tflite格式的代码进行转化，会报错，这是为什么呢

报什么错呢，我就是用这个转的呀

**Comment by chaotiaor** [comment]
这种错误， tensorflow.lite.python.convert.ConverterError: See console for info. 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lz"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 上午10:41
收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;; 
抄送: "逍遥游"<zhaortiang@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11)



 
你好，我使用tensorflow 2.0，使用你项目中转化模型成为tflite格式的代码进行转化，会报错，这是为什么呢
  
报什么错呢，我就是用这个转的呀

**Comment by 610265158** [comment]
你转的哪个模型

**Comment by chaotiaor** [comment]
face_landmark_shufflenetv2_0.75 ，这个模型

错误信息如下
 File "C:\Users\meice\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\lite\python\convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
b"'toco_from_protos' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n"

**Comment by 610265158** [comment]
> face_landmark_shufflenetv2_0.75 ，这个模型
> 
> 错误信息如下
> File "C:\Users\meice\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\lite\python\convert.py", line 200, in toco_convert_protos
> raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
> tensorflow.lite.python.convert.ConverterError: See console for info.
> b"'toco_from_protos' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n"

刚测试了，没有遇到这个问题啊，
ubuntu 16.04 ，  没有测试windows

**Comment by chaotiaor** [comment]
我是在windows下运行的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lz"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 上午10:57
收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;; 
抄送: "逍遥游"<zhaortiang@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11)



 
face_landmark_shufflenetv2_0.75 ，这个模型
 
错误信息如下
 File "C:\Users\meice\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\lite\python\convert.py", line 200, in toco_convert_protos
 raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
 tensorflow.lite.python.convert.ConverterError: See console for info.
 b"'toco_from_protos' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n"
  
刚测试了，没有遇到这个问题啊，
 ubuntu 16.04 ，  没有测试windows

**Comment by 610265158** [comment]
> 我是在windows下运行的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Lz"<notifications@github.com&gt;; 发送时间: 2019年11月15日(星期五) 上午10:57 收件人: "610265158/face_landmark"<face_landmark@noreply.github.com&gt;; 抄送: "逍遥游"<zhaortiang@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [610265158/face_landmark] 想问一下训练的最终指标是多少？ (#11) face_landmark_shufflenetv2_0.75 ，这个模型 错误信息如下 File "C:\Users\meice\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\lite\python\convert.py", line 200, in toco_convert_protos raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr)) tensorflow.lite.python.convert.ConverterError: See console for info. b"'toco_from_protos' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n" 刚测试了，没有遇到这个问题啊， ubuntu 16.04 ， 没有测试windows — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

把模型发我，我试一下，

**Comment by chaotiaor** [comment]
发到你的邮箱吗

**Comment by 610265158** [comment]
> 发到你的邮箱吗

对

**Comment by luckynote** [comment]
> 请问您最后在Mobilenet V2上训练的指标是多少(IPN or ION)？

IPN
| Method               | Common(%) | Challenging(%) | Fullset(%) |
| -------------------- | --------- | -------------- | ---------- |
| PIG 0.75x | 5.57      | 9.01           | 6.25       |

ION
| Method               | Common(%) | Challenging(%) | Fullset(%) |
| -------------------- | --------- | -------------- | ---------- |
| PIG 0.75  | 4.02     | 6.24        | 4.46     |
