### ISSUE TITLE
数据增强

### ISSUE THREAD

**Issue by NoodlesVision** [610265158/face_landmark#12]
你好，根据姿态去做数据增强，我只看到你代码检测姿态的代码
PRY = euler_angle.reshape([-1]).astype(np.float32) / 90.
label = np.concatenate([label, PRY, cla_label], axis=0)
请问你在哪根据姿态去做了数据曾广？你训练模型训练集就是用github代码里面的数据增强的代码吗？谢谢！

**Comment by 610265158** [comment]
> 你好，根据姿态去做数据增强，我只看到你代码检测姿态的代码
> PRY = euler_angle.reshape([-1]).astype(np.float32) / 90.
> label = np.concatenate([label, PRY, cla_label], axis=0)
> 请问你在哪根据姿态去做了数据曾广？你训练模型训练集就是用github代码里面的数据增强的代码吗？谢谢！

hi
根据姿态的增强属于数据类别平衡，是用了更粗糙的方式处理的， 可以参考一下balance 这个函数

**Comment by NoodlesVision** [comment]
ok，谢谢!

**Comment by 610265158** [comment]
solved
