### ISSUE TITLE
face = tf.saved_model.load(model)出错

### ISSUE THREAD

**Issue by mumuyanyan** [610265158/face_landmark#13]
return func(*args, **kwargs)
TypeError: load() missing 2 required positional arguments: 'tags' and 'export_dir'

这是什么原因呢？

**Comment by mumuyanyan** [comment]
我用的是vis.py

**Comment by 610265158** [comment]
tensorflow2 吗

**Comment by mumuyanyan** [comment]
> tensorflow2 吗

我用的是tensorflow1，但是用你的tf1版本也是一样的，是不是这个vis.py这能用tensorflow2来做？

**Comment by 610265158** [comment]
> > tensorflow2 吗
> 
> 我用的是tensorflow1，但是用你的tf1版本也是一样的，是不是这个vis.py这能用tensorflow2来做？

master 是tf2   ， tf1 分支是tensorflow1， 需要加载pb模型

**Comment by mumuyanyan** [comment]
> > > tensorflow2 吗
> > 
> > 
> > 我用的是tensorflow1，但是用你的tf1版本也是一样的，是不是这个vis.py这能用tensorflow2来做？
> 
> master 是tf2 ， tf1 分支是tensorflow1， 需要加载pb模型

好的，vis.py需要调整咯，谢谢
