### ISSUE TITLE
GPU使用率0%

### ISSUE THREAD

**Issue by JunGenius** [610265158/face_landmark#18]
你好作者，
我想请问下，我在训练时候，为什么GPU使用率一直是0%, 而CPU一直满负荷。
下面是我的配置:

   os.environ["CUDA_VISIBLE_DEVICES"] = "0"
   config.TRAIN = edict()
   config.TRAIN.process_num = 8
   config.TRAIN.prefetch_size = 20
   config.TRAIN.num_gpu = 1
   config.TRAIN.batch_size = 128
   config.TRAIN.log_interval = 10  
   config.TRAIN.epoch = 10000

训练日志：
![image](https://user-images.githubusercontent.com/10972816/71483597-8e16cc00-2843-11ea-815b-bd21ac5a14e3.png)

现在训练太慢了 ， 我是1个 RTX 2060 super显卡，是我哪里没改正确吗？
非常感谢。

**Comment by 610265158** [comment]
用的是gpu么

**Comment by JunGenius** [comment]
![J5Q0KWN`82{GJ@ %8O$3Z)L](https://user-images.githubusercontent.com/10972816/71498854-08be0680-2899-11ea-922e-6d3182aa77c7.png)

![Z@6PD)F{ PE@OF~I`OES( A](https://user-images.githubusercontent.com/10972816/71498895-3acf6880-2899-11ea-95a2-c4846ef4957b.png)

gpu没有占用， 用的是gpu ， 是我哪里配置错了么  ？

非常感谢你的解答。

**Comment by JunGenius** [comment]
> 用的是gpu么， gpu 显存有占用么

![J5Q0KWN`82{GJ@ %8O$3Z)L](https://user-images.githubusercontent.com/10972816/71499138-2c358100-289a-11ea-8056-dd7cfdbae1f6.png)

![Z@6PD)F{ PE@OF~I`OES( A](https://user-images.githubusercontent.com/10972816/71499139-2f307180-289a-11ea-8c66-0bdcc9d33ad5.png)

用的是gpu，但gpu没有占用 ，是我没配置正确，给配置成cpu了吗 ？ 我该如何跑gpu?

非常感谢你的解答。

**Comment by 610265158** [comment]
应该是跑了gpu了， 把batch size 设置稍小一点， cpu占用多是dataloader的原因

**Comment by JunGenius** [comment]
> 应该是跑了gpu了， 把batch size 设置稍小一点， cpu占用多是dataloader的原因

好，那我再试试，非常感谢。
还有个问题想请教你下，我现在想做疲劳检测，但现有的模型，在角度大或戴眼镜时候，闭眼检测的有点不理想，所以我想用自己标注的数据训练（增加一些检测不理想方面的数据），但我只标注了37个点，你说这样可行吗？可以达到理想的效果吗 ？

标注的37个点。
![image](https://user-images.githubusercontent.com/10972816/71504390-33698880-28b4-11ea-9ac6-4231acde64a8.png)

非常感谢你的解答。

**Comment by 610265158** [comment]
针对badcase加数据会好点

**Comment by JunGenius** [comment]
> 针对badcase加数据会好点

OK ,我再试试 ，非常感谢。
