### ISSUE TITLE
headpose是怎么计算的？

### ISSUE THREAD

**Issue by zhunge** [610265158/face_landmark#2]
你好，请问一下你的headpose计算的原理是什么？

**Comment by 610265158** [comment]
> 你好，请问一下你的headpose计算的原理是什么？

计算的代码在face_landmark/lib/dataset/headpose.py，
根据标准脸投影计算的

**Comment by zhunge** [comment]
> > 你好，请问一下你的headpose计算的原理是什么？
> 
> 计算的代码在face_landmark/lib/dataset/headpose.py，
> 根据标准脸投影计算的

请问headpose中的object_pts和reprojectsrc根据什么设置的？

**Comment by 610265158** [comment]
> > > 你好，请问一下你的headpose计算的原理是什么？
> > 
> > 
> > 计算的代码在face_landmark/lib/dataset/headpose.py，
> > 根据标准脸投影计算的
> 
> 请问headpose中的object_pts和reprojectsrc根据什么设置的？

抱歉，这段代码是很久之前的了，实现上也参考了其他的repo。
现在我的解释可能也不太准确，object_pts是统计的标准脸模型，根据检出的点投影来估计姿态。reprojectsrc，是用来重投影到原图上，画图用的。仅供参考 :)

**Comment by zhunge** [comment]
> > > > 你好，请问一下你的headpose计算的原理是什么？
> > > 
> > > 
> > > 计算的代码在face_landmark/lib/dataset/headpose.py，
> > > 根据标准脸投影计算的
> > 
> > 
> > 请问headpose中的object_pts和reprojectsrc根据什么设置的？
> 
> 抱歉，这段代码是很久之前的了，实现上也参考了其他的repo。
> 现在我的解释可能也不太准确，object_pts是统计的标准脸模型，根据检出的点投影来估计姿态。reprojectsrc，是用来重投影到原图上，画图用的。仅供参考 :)

感谢您的解答。请问楼主有object_pts计算的参考资料推荐吗？被这个问题折磨很久了

**Comment by 610265158** [comment]
> > > > > 你好，请问一下你的headpose计算的原理是什么？
> > > > 
> > > > 
> > > > 计算的代码在face_landmark/lib/dataset/headpose.py，
> > > > 根据标准脸投影计算的
> > > 
> > > 
> > > 请问headpose中的object_pts和reprojectsrc根据什么设置的？
> > 
> > 
> > 抱歉，这段代码是很久之前的了，实现上也参考了其他的repo。
> > 现在我的解释可能也不太准确，object_pts是统计的标准脸模型，根据检出的点投影来估计姿态。reprojectsrc，是用来重投影到原图上，画图用的。仅供参考 :)
> 
> 感谢您的解答。请问楼主有object_pts计算的参考资料推荐吗？被这个问题折磨很久了

这应该是一个统计出来的数据，平均脸模型， 这样计算出来的欧拉角不是很精确，但是误差可以接受。

**Comment by 610265158** [comment]
problem solved

**Comment by xuguozhi** [comment]
请问是用keypoint[136]-keypoint[138]的结果做pose输出准，还是opencv solvePnP准确？
