### ISSUE TITLE
移动端部署

### ISSUE THREAD

**Issue by xuguozhi** [610265158/face_landmark#25]
Hi，发现你的项目很棒，正好最近我在研究MNN，希望可以移植到移动端上面做测试。目前实现了PFLD的MNN，请问您的模型有和PFLD做过比较吗？

**Comment by 610265158** [comment]
没有比较过，

**Comment by ainrichman** [comment]
> 没有比较过，mnn可以直接转换

我试过转成MNN但是失败了，提示Strided Slice不支持，能否请你分享一下转成功的MNN呢？victorzuo@outlook.com

**Comment by 610265158** [comment]
等有时间，我会转一个试试，
可以用tf1 分支转，如果 不支持就用mobilnenet， 或者修改对应层的实现就行

**Comment by xuguozhi** [comment]
For the shufflenetv2 model in tf1,
`./MNNConvert -f TF --modelFile keypoints.pb  --MNNModel keypoints.mnn --bizCode MNN`
 I met these error:
`Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::FusedBatchNorm`
My MNN is 0.2.1.7

**Comment by 610265158** [comment]
把batchnorm的trainging_flag 改成constant

**Comment by xuguozhi** [comment]
对tf实属小白，请问在哪里修改

**Comment by 610265158** [comment]
我来转一个

**Comment by xuguozhi** [comment]
Got it! THX

**Comment by fire717** [comment]
大佬空了可以转下mnn吗 我用转了不报错但是说结果没有对齐  试过pb2tnn和tf2onnx再onnx2tnn都一样

**Comment by BrownOfSummer** [comment]
转换成ncnn的过程同样出现了Strided Slice的问题

**Comment by fire717** [comment]
我通过自己修改模型结构然后重新训练然后转tnn成功了，ncnn应该也可以。
