### ISSUE TITLE
请问，windows不支持吗？

### ISSUE THREAD

**Issue by yangjituan** [610265158/face_landmark#3]
Can't pickle local object 'DataFromGenerator.__init__.<locals>.<lambda>'
这个，没找到哪里用了pickle，不知道怎么改，方便告知吗，谢谢？

**Comment by yangjituan** [comment]
WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
请问，如果想在windows下运行，需要怎么改这个，谢谢

**Comment by 610265158** [comment]
> WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
> 请问，如果想在windows下运行，需要怎么改这个，谢谢

抱歉windows没有测试过哟， 好像是tensorpack，多线程加载数据的原因
