### ISSUE TITLE
some error occurred when i convert the model to MNN model~

### ISSUE THREAD

**Issue by MirrorYuChen** [610265158/face_landmark#4]

**Comment by 610265158** [comment]
bn layer should set as False, you should rebuild the graph with bn training flag as False.

**Comment by 610265158** [comment]
> the details of error informations is below:
> 
> {19-10-02 11:56}mirror:~/MNN/tools/converter/build@master✗✗✗✗✗✗ mirror% ./MNN
> Convert -f TF --modelFile keypoints.pb --MNNModel xxx.mnn --bizCode biz
> MNNConverter Version: 0.0.0.1 - MNN @ 2018
> 
> Start to Convert Other Model Format To MNN Model...
> terminate called after throwing an instance of 'Error'
> what(): [11:57:21] /home/mirror/MNN/tools/converter/source/tensorflow/TmpG
> raph.cpp:316: Check failed: inputNode->opType == "Const" ==> FusedBatchNorm|SpaceToBatchND Lack Const Tensor[1] 10624 abort (core dumped) ./MNNConvert -f TF --modelFile keypoints.pb
> --MNNModel xxx.mnn --bizCode biz
> 
> I found there is an similar issues in MNN project:
> [alibaba/MNN#358](https://github.com/alibaba/MNN/issues/358)
> 
> 如果使用了bn，生成pb时将bn层training参数设为False；
> 如果使用了dilation conv，需要固定输入图像大小，然后重新生成pb。
> 
> I wanna to kown how to set these layers, can you give me some advice ?

You should rebuild the graph with bn training flag as False.
rebuild the graph with the bn layer as False, load the params, and save it.

**Comment by MirrorYuChen** [comment]
You mean set flag: use_batch_norm to false?

**Comment by 610265158** [comment]
> You mean set flag: use_batch_norm to false?

In tensorflow, a placeholder was used to control the bn layer,  so when inference a bool value should be feded.  e.g. is_training=training in below codes
net, end_points=shufflenet_v2(images,is_training=training,depth_multiplier='1.0')

in some converter, including tflite, the flag shoule be set as a constant.

**Comment by MirrorYuChen** [comment]
Thank you very much, I will have a try~
