### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by jianghongsun** [610265158/face_landmark#43]
感谢作者的分享  训练是使用tensorflow-gpu=2.0.0  
出现ModuleNotFoundError: No module named 'tensorflow.contrib'

如何设置分支 tensorflow-gpu2.0.0 或者tensorflow-gpu 1.4.0 ，麻烦你有空解答下 谢谢

**Comment by 610265158** [comment]
没看懂你的问题， tensorflow2 是没有contrib 的

**Comment by jianghongsun** [comment]
已经解决了，谢谢分享 向大佬学习
