### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by jianghongsun** [610265158/face_landmark#44]
模型保存时存在tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./model/epoch_0_val_loss307.512268\variables; No such file or directory

实际上有model文件夹？ 麻烦大佬，有空解答下  谢谢

**Comment by 610265158** [comment]
你是在什么环境下跑的呢，  可以修改一下保存的路径

**Comment by jianghongsun** [comment]
win10 环境下 tensorlow-gpu 2.0  这个问题解决了 把路径修改为
 config.MODEL.model_path = '.\\model\\'   可以了 
但我又遇到一个问题：将enable_function 设置为True  
 Epoch: 2, Train Loss: nan, Test Loss: nan Time consume: 9.55 这个该如何调整呢？麻烦你，有空时解答下？ 谢谢

**Comment by jianghongsun** [comment]
已经运行成功，谢谢

**Comment by BrownOfSummer** [comment]
@jianghongsun 请问你是怎么解决ZeroDivisionError问题的呢？

**Comment by monk-gyai** [comment]
> 已经运行成功，谢谢

大佬 可以问一下你是怎么解决ZeroDivisionError问题的么 我也遇到了同样的问题

**Comment by 610265158** [comment]
ZeroDivisionError，
应该是数据集小了，

可以直接使用pytorch 的分支来做，tensorflow 不好用

**Comment by monk-gyai** [comment]
我知道问题了 是tensorpack的版本不对 换成0.9.9就好了 是读数据的问题，我已经能跑通了 感谢













在 2021-07-26 16:47:25，"Lz" ***@***.***> 写道：

ZeroDivisionError，
应该是数据集小了，

可以直接使用pytorch 的分支来做，tensorflow 不好用
