### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by ycdhqzhiai** [610265158/face_landmark#9]
@610265158 你好，请问下加载模型报
graph_def.ParseFromString(fid.read())
google.protobuf.message.DecodeError: Error parsing message
这个该怎么解决啊

**Comment by 610265158** [comment]
> @610265158 你好，请问下加载模型报
> graph_def.ParseFromString(fid.read())
> google.protobuf.message.DecodeError: Error parsing message
> 这个该怎么解决啊

有更详细的堆栈信息么？

**Comment by ycdhqzhiai** [comment]
![image](https://user-images.githubusercontent.com/12273405/67650214-09a8e980-f977-11e9-88ff-8d84dbeee89b.png)

并没有

**Comment by 610265158** [comment]
tf 什么版本呢

**Comment by ycdhqzhiai** [comment]
1.14

**Comment by 610265158** [comment]
> 1.14

等我有空测一下

**Comment by ycdhqzhiai** [comment]
好的，非常感谢回复

**Comment by 610265158** [comment]
> 好的，非常感谢回复

我刚测试了一下，没有发现什么问题呀

**Comment by ycdhqzhiai** [comment]
![image](https://user-images.githubusercontent.com/12273405/67654444-94461480-f988-11e9-98a1-8dda0aaadf42.png)
![image](https://user-images.githubusercontent.com/12273405/67654468-a922a800-f988-11e9-8c83-5effb03215f9.png)

clone之后，只是把pb名字改了，没问题啊

**Comment by 610265158** [comment]
> ![image](https://user-images.githubusercontent.com/12273405/67654444-94461480-f988-11e9-98a1-8dda0aaadf42.png)
> ![image](https://user-images.githubusercontent.com/12273405/67654468-a922a800-f988-11e9-8c83-5effb03215f9.png)
> 
> clone之后，只是把pb名字改了，没问题啊

是tf1 的分支么

**Comment by ycdhqzhiai** [comment]
是的，clone之后git checkout tf1

**Comment by 610265158** [comment]
> 是的，clone之后git checkout tf1

不太确定是哪里出了问题了

**Comment by ycdhqzhiai** [comment]
好的，麻烦你了，我再试试
